Fix issue #1234: Add new feature
ALX-Students-Contribution/ALX_Dark_Mode_Extension pull request #15
Opened 2023-04-04 13:08 UTC by Tosinkuzzy

Automatic time zone switches
from daylight mood 
to night mood

2023-04-04 13:34 UTC, DestinedCodes requested changes

2023-04-04 13:34 UTC, DestinedCodes commented on README.md
> +        <img src="https://avatars.githubusercontent.com/u/99524902?v=4" width="100px" alt="Tosinkuzzy" title="Tosinkuzzy" />
```suggestion
        <img src="paste the url to your avatar here" width="100px" alt="Tosinkuzzy" title="Tosinkuzzy" />
```
You would have to paste the URL to your profile avatar here, so that it displays the right avatar with your name

2023-04-04 14:05 UTC, Tosinkuzzy commented
Automatic time zone switches
from daylight mood
to night mood

2023-04-04 15:01 UTC, DestinedCodes requested changes

2023-04-04 15:01 UTC, DestinedCodes commented on README.md
> +      </a>
1. The `<td>` cloding tag seems to be missing (Please do add that to avoid redundancy)
2. Instead of adding a new column on the row, we suggest you remove the newly added column and replace you details as the third contributor.

Also please do check out other open issues to find one you could contribute to

2023-04-13 08:49 UTC, DestinedCodes commented
This issue is ckosed since were no longwr adding contribitors manually, make a merged pulll request on the codebase and youll be featured automatically

2023-04-13 08:49 UTC, closed without merging